### ISSUE TITLE
Where is  'FSharp.Compiler.Interactive.Settings' ?

### ISSUE THREAD

**Issue by goswinr** [ronaldschlenker/PrettyFsi#3]
I get the message: `The type referenced through 'FSharp.Compiler.Interactive.InteractiveSession' is defined in an assembly that is not referenced. You must add a reference to assembly 'FSharp.Compiler.Interactive.Settings'.`

I saw it here: https://github.com/ronaldschlenker/PrettyFsi/blob/7417b9e3758f6a518d329f9eb2fdde36bb2e95d6/src/PrettyFsi/PrettyFsi.fsproj#L28 but can't find it on nuget.

(on net48)

**Comment by goswinr** [comment]
ah, it is exlplained here: 
https://github.com/ronaldschlenker/PrettyFsi/blob/main/devDependeicies/README.md
on net48 I had to add a refrence to it.
formatting still did not work. Maybe it only works when run via `dotnet fsi`

**Comment by SchlenkR** [comment]
`FSharp.Compiler.Interactive.Settings.dll` is not part of the `FSharp.Compiler.Service` package, and I wasn't sure if the license allows including it in an open source repository. It is needed at compile time only, since the interactive sessions used in VS, VS Code and Rider all distribute the dll themselves and instanciate the `fsi` object that is implemented in the `FSharp.Compiler.Interactive.Settings.dll`. Since the whole dotnet stuff is MIT, I guess it should be allowed to include a compile-time version of `FSharp.Compiler.Interactive.Settings.dll` in this repo - what do you think?

**Comment by goswinr** [comment]
I run my scripts via `FSharp.Compiler.Service` directly. I am bound to net48 by the host ( Rhino3d) It works fine. Where do i get the missing FSharp.Compiler.Interactive.Settings.dll officially from? I never needed it.

**Comment by SchlenkR** [comment]
@goswinr Please excuse the delayed reply. There seems to be no `FSharp.Compiler.Interactive.Settings` NuGet package available, and it seems that it's part of the used .Net SDK or .Net Framework. PrettyFsi needs the dll only as a compile time dependency (and hopefully, its API will remain compatible). During runtime, the dll is loaded and resolvable - at least in the hosts I know. I guess that applies to Rhino3D as well (it seems to be configurable when hosting FSI; see attached screenshot). If there's an issue with that, please let me know. Thank you

![image](https://user-images.githubusercontent.com/472222/149007916-8f38f847-0724-4f5e-937d-811edc3a7339.png)

**Comment by goswinr** [comment]
Thanks! Do you know where can I get `FSharp.Compiler.Interactive.Settings.dll` from? (for net48) let's assume there is no visual studio or donet sdk installed. Just the FCS nuget. 
Setting the auxLib to true in  `let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration(settings,useFsiAuxLib=true) ` crashes with a `StopProcessingExn` because it can't find the Settings.dll.
Is this an issue for https://github.com/dotnet/fsharp ?

**Comment by SchlenkR** [comment]
For **dotnet**, the `FSharp.Compiler.Interactive.Settings.dll` is shipped with the SDKs, so for example here:

```
C:\Program Files\dotnet\sdk\5.0.210\FSharp\FSharp.Compiler.Interactive.Settings.dll`.
```

For **.Net Framework**, the only location I found was in 2 Visual Studio folders:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\FSharp.Compiler.Interactive.Settings.dll

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\FSharp.Compiler.Interactive.Settings.dll
```

The Visual Studio F# Interactive tooling uses the first of the two locations (using `fsi.GetType().Assembly.Location;;`). 

> Where do i get the missing FSharp.Compiler.Interactive.Settings.dll officially from

For .Net FW, I don't know where you get it _officially_ from, and I don't know if it is permitted redistributing the dll that is shipped with Visual Studio. [Here](https://github.com/dotnet/fsharp/issues/7950#issuecomment-565449011) is a related issue. I also don't know why it's not part of `FSharp.Compiler.Service` NuGet package or why there isn't a separate `FSharp.Compiler.Interactive.Settings` package.

> Is this an issue for https://github.com/dotnet/fsharp ?

For dotnet, that might not be an issue since it is shipped with the SDKs. For .Net FW, might be an issue.

**Comment by goswinr** [comment]
see https://github.com/dotnet/fsharp/issues/12598
